export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_EBOOK = "GET_EBOOK";
export const EBOOK_LOADING = "EBOOK_LOADING";
export const UNASSIGNED_EBOOKS_LOADING = "UNASSIGNED_EBOOKS_LOADING";
export const ASSIGNED_EBOOKS_LOADING = "ASSIGNED_EBOOKS_LOADING";
export const EBOOK_NOT_FOUND = "EBOOK_NOT_FOUND";

export const CLEAR_CURRENT_EBOOK = "CLEAR_CURRENT_EBOOK";
export const CLEAR_ASSIGNED_EBOOKS = "CLEAR_ASSIGNED_EBOOKS";
export const CLEAR_UNASSIGNED_EBOOKS = "CLEAR_UNASSIGNED_EBOOKS";
export const CLEAR_STUDENTS = "CLEAR_STUDENTS";
export const CLEAR_STUDENT = "CLEAR_STUDENT";
export const CLEAR_WEEKLY_REPORT = "CLEAR_WEEKLY_REPORT";

export const GET_EBOOKS = "GET_EBOOKS";
export const GET_UNASSIGNED_EBOOKS = "GET_UNASSIGNED_EBOOKS";
export const GET_ASSIGNED_EBOOKS = "GET_ASSIGNED_EBOOKS";
export const GET_STUDENT = "GET_STUDENT";
export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const STUDENTS_LOADING = "STUDENTS_LOADING";
export const GET_WEEKLY_REPORT = "GET_WEEKLY_REPORT";
export const WEEKLY_REPORT_LOADING = "WEEKLY_REPORT_LOADING";
